name: Automated API Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      APIFOX_ACCESS_TOKEN: ${{ secrets.APIFOX_ACCESS_TOKEN }}
    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js environment
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Apifox CLI
      run: npm install -g apifox-cli

    - name: Running Test Scenario1
      run: apifox run --access-token $APIFOX_ACCESS_TOKEN -t 8239446 -e 44374114 -d 4231571 -r html,cli

    - name: Running Test Scenario2
      run: apifox run --access-token $APIFOX_ACCESS_TOKEN -t 8225023 -e 44374117 -n 1 -r html,cli

    